In [102]:
import pandas as pd

frame = pd.read_csv("Q:\\3_Projects\\NVI\\2025\\nvi_survey_data_2025_20260226.csv")
datadict = pd.read_csv(
    "P:\\2025_Projects\\NVI25\\Development\\Workspace\\codebook_cleanup\\nvi_codebook_organization_20260225.csv", 
    encoding='cp1252',
    keep_default_na=False
)

C:\Users\mike\AppData\Local\Temp\ipykernel_23968\2419447629.py:3: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  frame = pd.read_csv("Q:\\3_Projects\\NVI\\2025\\nvi_survey_data_2025_20260226.csv")

In [106]:
COLUMN = 74

if COLUMN < 4: raise ValueError("Coded columns start at 4")
missing_cols = {16, 17}
if COLUMN in missing_cols: raise ValueError(f"Some columns are missing: {missing_cols}")

question = datadict[['label', 'topic_text', 'question_text']].drop_duplicates(subset='label').iloc[COLUMN]

if pd.notna(question["topic_text"]):
    print(question["topic_text"])

print(question["question_text"])

values = datadict[datadict['label'] == question["label"]]
texts = values[["code", "text"]].set_index("code")

(
    frame[question["label"]]
    .astype(pd.Int64Dtype())
    .value_counts(dropna=False)
    .to_frame()
    .join(texts, how="left")
    .sort_index()
    .fillna({"text": "[BLANK]"})
)

Please indicate how much you agree to the following statements:
I plan to stay in my neighborhood for the next 12 months

,count,text
Stay_12_Months:Agreement_Statements_Access_and_Support,,
0,123,N/A
1,328,Strongly Disagree
2,265,Somewhat Disagree
3,605,Neither Agree or Disagree
4,1012,Somewhat Agree
5,4330,Strongly Agree
<NA>,49,[BLANK]

In [101]:
texts

                           text
code
0                           NaN
1             Strongly Disagree
2             Somewhat Disagree
3     Neither Agree or Disagree
4                Somewhat Agree
5                Strongly Agree

In [89]:
qs[qs["label"].str.lower().str.contains("months")]

,label,topic_text,question_text
33,SchoolProgram_Sports_Tutoring_Participation:Yo...,Thinking about the youth (under 18) in your ho...,Youth (under 18) in my household have enrolled...
74,Stay_12_Months:Agreement_Statements_Access_and...,Please indicate how much you agree to the foll...,I plan to stay in my neighborhood for the next...
77,Not_Able_Pay_Rent_Mortgage:Rent_Utilities_Past...,During the past 12 months,â€¦was there a time when you were not able to ...
78,Electric_Water_Threatened_Shutoff:Rent_Utiliti...,During the past 12 months,"â€¦was there a time when an electric, gas, oil..."
80,Finance_Prevent_Healthcare:Needs_In_Past_12_Mo...,During the past 12 monthsâ€¦,â€¦have financial concerns prevented you or so...
81,Not_Find_Affordable_Housing:Needs_In_Past_12_M...,During the past 12 monthsâ€¦,â€¦have you wanted to move somewhere else in t...
82,At_Risk_Losing_Home:Needs_In_Past_12_Months,During the past 12 monthsâ€¦,â€¦have you ever been at risk of losing your h...
115,Purchased a lot or lots near my home:In_The_La...,"In the last 12 months, I have… (Select all tha...",NaN
116,Cleaned up or improved lot(s) that I own:In_Th...,"In the last 12 months, I have… (Select all tha...",NaN
117,Cleaned up or improved lot(s) that I do not ow...,"In the last 12 months, I have… (Select all tha...",NaN
118,Secured or improved vacant housing:In_The_Last...,"In the last 12 months, I have… (Select all tha...",NaN
119,Cleaned up or improved alley ways:In_The_Last_...,"In the last 12 months, I have… (Select all tha...",NaN
120,Cleaned up or improved park/open spaces:In_The...,"In the last 12 months, I have… (Select all tha...",NaN
121,I have not participated in any of these activi...,"In the last 12 months, I have… (Select all tha...",NaN